# Generated by Django 2.2.1 on 2019-05-28 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='people',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
