# Generated by Django 2.2.1 on 2019-05-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190528_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
